// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACAz9vu6HU2v6ZuhH_sIzhhlvAUVnQP-M',
    appId: '1:1080851371364:web:18f05f657db7c1c89ad671',
    messagingSenderId: '1080851371364',
    projectId: 'visualodometryapp',
    authDomain: 'visualodometryapp.firebaseapp.com',
    storageBucket: 'visualodometryapp.appspot.com',
    measurementId: 'G-CW7XXQNCVW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMJMMfVxnZa-HtDLo3fNNfE3Op4saSda4',
    appId: '1:1080851371364:android:2223c7e454121b289ad671',
    messagingSenderId: '1080851371364',
    projectId: 'visualodometryapp',
    storageBucket: 'visualodometryapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVZWA3YhLivkv-8mmpfigUDwVZccbvI08',
    appId: '1:1080851371364:ios:f30f3be10109a5c39ad671',
    messagingSenderId: '1080851371364',
    projectId: 'visualodometryapp',
    storageBucket: 'visualodometryapp.appspot.com',
    iosClientId: '1080851371364-1srjinqc2htto8hvhjihue2g2pq3hqbt.apps.googleusercontent.com',
    iosBundleId: 'com.example.visualodometryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVZWA3YhLivkv-8mmpfigUDwVZccbvI08',
    appId: '1:1080851371364:ios:f30f3be10109a5c39ad671',
    messagingSenderId: '1080851371364',
    projectId: 'visualodometryapp',
    storageBucket: 'visualodometryapp.appspot.com',
    iosClientId: '1080851371364-1srjinqc2htto8hvhjihue2g2pq3hqbt.apps.googleusercontent.com',
    iosBundleId: 'com.example.visualodometryApp',
  );
}
